version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "6033:3306"
###< doctrine/doctrine-bundle ###
